name: PR-CI-CD

on:
  pull_request_target:

jobs:
  close-external-prs:
    uses: crickets-and-comb/shared/.github/workflows/block_outside_PRs.yml@main
    with:
      ALLOWED_ORG: "crickets-and-comb"
    secrets:
      ORG_READ_TOKEN: ${{ secrets.ORG_READ_TOKEN }}

  CI_CD:
    needs: close-external-prs
    uses: crickets-and-comb/bfb_delivery_desktop/.github/workflows/CI_CD.yml@feature/KalebCoberly/bare_ui_setup
