name: PR-QC

on:
  pull_request_target:

jobs:
  close-external-prs:
    uses: crickets-and-comb/shared/.github/workflows/block_outside_PRs.yml@main
    with:
      ALLOWED_ORG: "crickets-and-comb"
    secrets:
      ORG_READ_TOKEN: ${{ secrets.ORG_READ_TOKEN }}

  QC:
    needs: close-external-prs
    uses: crickets-and-comb/bfb_delivery_desktop/.github/workflows/QC.yml@main
    with:
      # Passing PR merge ref to avoid using forked PR branch head ref allowing malicious workflows to run.
      REF_TO_CHECKOUT: ${{ format('refs/pull/{0}/merge', github.event.pull_request.number) }}
    secrets:
      CHECKOUT_SHARED: ${{ secrets.CHECKOUT_SHARED }}
