name: CI-CD

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      DISABLE_ELECTRON_TESTS:
        description: 'Set to "true" to skip Electron UI tests.'
        type: boolean
        default: false
    secrets:
      CHECKOUT_SHARED:
        description: "Org or repo checkout token."
        required: true
  workflow_dispatch:
    inputs:
      DISABLE_ELECTRON_TESTS:
        description: 'Set to "true" to skip Electron UI tests.'
        type: boolean
        default: false
  schedule:
    - cron: "0 1 * * 0" # Weekly on Sunday at 1:00 a.m.

env:
  DISABLE_ELECTRON_TESTS_DEFAULT: false

defaults:
  run:
    shell: bash -el {0}

jobs:
  validate-and-set-inputs:
    name: Validate and set inputs
    runs-on: ubuntu-latest
    outputs:
      DISABLE_ELECTRON_TESTS: ${{ steps.validate-disable-electron-tests.outputs.DISABLE_ELECTRON_TESTS }}

    steps:
      - name: Validate DISABLE_ELECTRON_TESTS
        id: validate-disable-electron-tests
        env:
          DISABLE_ELECTRON_TESTS: ${{ inputs.DISABLE_ELECTRON_TESTS }}
        run: |
          if [[ -z "$DISABLE_ELECTRON_TESTS" ]]; then
            echo "DISABLE_ELECTRON_TESTS is not set, using default: $DISABLE_ELECTRON_TESTS_DEFAULT"
            DISABLE_ELECTRON_TESTS=$DISABLE_ELECTRON_TESTS_DEFAULT
          fi

          echo "DISABLE_ELECTRON_TESTS=$DISABLE_ELECTRON_TESTS" >> $GITHUB_OUTPUT

  qc-and-test:
    needs: validate-and-set-inputs
    runs-on: ubuntu-latest
    name: Run Linting, Security, Tests, and Dist Build

    steps:
      - name: Set ref
        id: set-ref
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            echo "Using PR merge ref to avoid running workflows on forked repo."
            echo "ref=refs/pull/${{ github.event.pull_request.number }}/merge" >> $GITHUB_OUTPUT
          elif [[ -n "${{ github.ref || '' }}" ]]; then
            echo "Using github.ref"
            echo "ref=${{ github.ref }}" >> $GITHUB_OUTPUT
          else
            echo "Using fallback default ref"
            echo "ref=refs/heads/main" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.set-ref.outputs.ref }}
          token: ${{ secrets.CHECKOUT_SHARED }}

      - name: Set up Node with Volta
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run security check
        run: npm run security

      - name: Start virtual display (Xvfb)
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run tests (skip Electron UI tests in headless)
        run: npx cross-env DISABLE_ELECTRON_TESTS=${{ needs.validate-and-set-inputs.outputs.DISABLE_ELECTRON_TESTS }} npm run test

      - name: Test-build the distribution
        run: npm run dist
