name: Release

on:
  workflow_dispatch:

jobs:
  CI_CD:
    uses: crickets-and-comb/bfb_delivery_desktop/.github/workflows/CI_CD.yml@feature/KalebCoberly/bare_ui_setup

  release:
    needs: CI_CD
    runs-on: ubuntu-latest
    name: Build and Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node using Volta
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: npm ci

      - name: Build and Publish with electron-builder
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release
