name: Release

on:
  workflow_dispatch:

jobs:
  QC:
    uses: crickets-and-comb/bfb_delivery_desktop/.github/workflows/QC.yml@main
    secrets:
      CHECKOUT_SHARED: ${{ secrets.CHECKOUT_SHARED }}

  release:
    needs: QC
    runs-on: ubuntu-latest
    name: Build and Release

    steps:
      - name: Set ref
        id: set-ref
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            echo "Using PR merge ref to avoid running workflows on forked repo."
            echo "ref=refs/pull/${{ github.event.pull_request.number }}/merge" >> $GITHUB_OUTPUT
          elif [[ -n "${{ github.ref || '' }}" ]]; then
            echo "Using github.ref"
            echo "ref=${{ github.ref }}" >> $GITHUB_OUTPUT
          else
            echo "Using fallback default ref"
            echo "ref=refs/heads/main" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.set-ref.outputs.ref }}
          submodules: recursive
          token: ${{ secrets.CHECKOUT_SHARED }}

      - name: Set up Node using Volta
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: npm ci

      - name: Build and Publish with electron-builder
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release
